"""Evidence-backed reporting and MCP connection scaffolding.

Every line of the generated report is derived from the ledger, and each fact
carries the claim id that supports it. If a fact has no claim, it does not appear
in the report -- there is no narrative layer that gets to fill the gaps.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .evidence import EvidenceLedger
from .ingest.pipeline import write_json


def write_report(
    output_dir: Path,
    manifest: dict[str, Any],
    ledger: EvidenceLedger,
    provenance: dict[str, Any] | None = None,
) -> Path:
    """Write ``report/dataset-report.md`` and return its path."""
    report_dir = output_dir / "report"
    report_dir.mkdir(parents=True, exist_ok=True)
    path = report_dir / "dataset-report.md"
    path.write_text(_render(manifest, ledger, provenance or {}), encoding="utf-8")
    return path


def write_mcp_config(
    output_dir: Path, *, source_dir: Path, mode: str, python_executable: str = "python3"
) -> Path:
    """Write ``mcp/`` connection files for MCP hosts.

    The same server definition is emitted for every host, because the MCP
    boundary is host-agnostic by design; only the file a host reads differs.
    """
    mcp_dir = output_dir / "mcp"
    mcp_dir.mkdir(parents=True, exist_ok=True)

    definition = {
        "command": python_executable,
        "args": ["-m", "data2agent.cli", "serve", str(output_dir), "--mode", mode],
        "env": {},
    }
    write_json(mcp_dir / "server.json", {"mcpServers": {"data2agent": definition}})
    (mcp_dir / "USAGE.md").write_text(
        _render_usage(output_dir, source_dir, mode, definition), encoding="utf-8"
    )
    return mcp_dir


def _render(manifest: dict[str, Any], ledger: EvidenceLedger, provenance: dict[str, Any]) -> str:
    convention = manifest.get("missing_value_convention", {})
    lines: list[str] = [
        "# Dataset report",
        "",
        "Generated by Data2Agent. Every statement below is backed by a claim in",
        "`evidence.json`; the claim id in brackets is the lookup key for",
        "`get_evidence(claim_id=...)`. Fields that were not determined are named as",
        "such and are never filled in by inference.",
        "",
        "## Identity",
        "",
        f"- Dataset id: `{manifest.get('dataset_id', '')}`",
        f"- Files: {manifest.get('file_count', 0)}",
        f"- Total bytes: {manifest.get('total_bytes', 0)}",
        f"- Manifest version: {manifest.get('manifest_version', '')}",
        "",
        "## This ingest run",
        "",
        # From provenance.json, not the manifest: the manifest must stay
        # timestamp-free so repeat ingests compare byte-for-byte.
        f"- Ingested at: {provenance.get('started_at', 'not recorded')}",
        f"- Finished at: {provenance.get('finished_at', 'not recorded')}",
        f"- Duration: {provenance.get('duration_seconds', 'not recorded')} s",
        f"- Tool: {provenance.get('tool', {}).get('name', 'data2agent')} "
        f"{provenance.get('tool', {}).get('version', '')}",
        "- Source verified unchanged: "
        f"{provenance.get('source_verified_unchanged', 'not recorded')}",
        "",
        "## Missing-value convention",
        "",
        f"- Applied: `{convention.get('id', 'unknown')}`",
        f"- Source: {convention.get('source', 'not recorded')}",
        f"- Tokens resolved to missing: {_token_list(convention)}",
        "- Tokens such as `unknown`, `-` and `?` are **never** resolved to missing by a "
        "built-in convention; they are counted separately below.",
        "",
    ]

    formats = manifest.get("formats", {})
    if formats:
        lines += ["## Formats", ""]
        lines += [f"- `{name}`: {count} file(s)" for name, count in formats.items()]
        lines.append("")

    metadata_files = manifest.get("metadata_files", [])
    lines += ["## Metadata files", ""]
    if metadata_files:
        for item in metadata_files:
            lines.append(f"- `{item['path']}` — {item['convention']} ({item['note']})")
    else:
        lines.append("- None recognised by filename convention.")
    lines.append("")

    tables = manifest.get("tables", {})
    if tables:
        lines += ["## Tables", ""]
        for path, profile in tables.items():
            lines += [
                f"### `{path}`",
                "",
                f"- Rows: {profile.get('rows', 0)}",
                f"- Columns: {profile.get('column_count', 0)}",
                "",
                "| column | observed shape | missing | (empty) | (tokens) "
                "| unresolved tokens | claim |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
            for column in profile.get("columns", []):
                claim = _find_claim(ledger, path, "table.column-dtype", column["name"])
                ambiguous = column.get("ambiguous_tokens_seen", {})
                unresolved = (
                    ", ".join(f"`{token}`×{count}" for token, count in ambiguous.items()) or "—"
                )
                lines.append(
                    f"| `{column['name']}` | {column['dtype']} | {column['missing']} | "
                    f"{column.get('missing_empty', 0)} | {column.get('missing_sentinel', 0)} | "
                    f"{unresolved} | `{claim}` |"
                )
            lines.append("")

    identifiers = manifest.get("identifiers", [])
    lines += ["## Identifiers detected", ""]
    if identifiers:
        lines.append(
            "Detected by pattern match only. No identifier was resolved; resolution is "
            "a FAIR check; run `data2agent assess` for it."
        )
        lines.append("")
        for hit in identifiers:
            lines.append(f"- `{hit['scheme']}` `{hit['value']}` — {hit['source']}:{hit['line']}")
    else:
        lines.append("- None detected.")
    lines.append("")

    lines += [
        "## Not determined",
        "",
        "The following were **not** assessed and must not be inferred from this report:",
        "",
        "- Cross-file relationships between tables and metadata records.",
        "- The scientific meaning of any column, including units and controlled terms.",
        "- Whether unresolved tokens (`unknown`, `-`, `?`, ...) denote missing values. "
        "Tokens the applied convention *does* resolve are counted in the missing column above.",
        "- Whether any detected identifier resolves, or is correct.",
        "- Any FAIR indicator. Run `data2agent assess <output>` for the FAIR profile; "
        "it is a separate layer and is not reflected in this report.",
        "",
    ]

    warnings = manifest.get("warnings", [])
    lines += ["## Warnings", ""]
    lines += [f"- {warning}" for warning in warnings] if warnings else ["- None."]
    lines.append("")
    lines += [f"Claims recorded: {len(ledger)}.", ""]
    return "\n".join(lines)


def _token_list(convention: dict[str, Any]) -> str:
    tokens = convention.get("tokens", [])
    return ", ".join(f"`{token}`" for token in tokens) or "none"


def _find_claim(ledger: EvidenceLedger, subject: str, check: str, field: str) -> str:
    for record in ledger.query(subject=subject, check=check):
        if any(item.field == field for item in record.evidence):
            return record.claim_id
    return "—"


def _render_usage(output_dir: Path, source_dir: Path, mode: str, definition: dict[str, Any]) -> str:
    block = json.dumps({"mcpServers": {"data2agent": definition}}, indent=2)
    command = " ".join([definition["command"], *definition["args"]])
    return f"""# Connecting this dataset's MCP server

This server exposes the dataset ingested from `{source_dir}` in mode `{mode}`.
It is read-only: it never writes to the dataset, and it withholds content from any
file whose checksum no longer matches `manifest.json`.

## Requirements

```bash
pip install 'data2agent[mcp]'
```

## Claude Code

```bash
claude mcp add data2agent -- {command}
```

## Codex and other hosts reading an MCP JSON config

```json
{block}
```

## Any host

The server speaks MCP over stdio and knows nothing about which host started it.
Run it directly with:

```bash
{command}
```

## Available tools in mode `{mode}`

Call `dataset_inventory` first, then `inspect_table` / `get_metadata` for
specifics, and `get_evidence` before asserting anything. A statement with no
supporting claim is unsupported -- report it as unknown.

## FAIR assessment

FAIR is a separate profile, not part of this server's default surface. Run it
with:

```bash
data2agent assess {output_dir}
```

or start the server in a FAIR mode (`--mode fair-rules` to expose the canonical
rules, `--mode fair-deterministic` to expose the checks as well). Results marked
`unknown` are results: they must be reported as unknown, not reasoned into a
verdict.

## Output directory

```
{output_dir}
├── manifest.json     what the dataset is (deterministic; no timestamps)
├── provenance.json   what this ingest run was (time, duration, tool version)
├── evidence.json     claim -> evidence -> file -> checksum
├── assessment.json   written by `data2agent assess`
├── mcp/              this directory
└── report/           evidence-backed Markdown report
```

Timestamps are kept out of the manifest so that repeated ingests of identical
bytes compare byte-for-byte. They are still reachable: `dataset_inventory`,
`get_provenance`, and `dataset://provenance`.
"""
