"""Evidence-backed reporting and MCP connection scaffolding.

Every line of the generated report is derived from the ledger, and each fact
carries the claim id that supports it. If a fact has no claim, it does not appear
in the report -- there is no narrative layer that gets to fill the gaps.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .evidence import EvidenceLedger
from .ingest.pipeline import write_json


def write_report(output_dir: Path, manifest: dict[str, Any], ledger: EvidenceLedger) -> Path:
    """Write ``report/dataset-report.md`` and return its path."""
    report_dir = output_dir / "report"
    report_dir.mkdir(parents=True, exist_ok=True)
    path = report_dir / "dataset-report.md"
    path.write_text(_render(manifest, ledger), encoding="utf-8")
    return path


def write_mcp_config(
    output_dir: Path, *, source_dir: Path, mode: str, python_executable: str = "python3"
) -> Path:
    """Write ``mcp/`` connection files for MCP hosts.

    The same server definition is emitted for every host, because the MCP
    boundary is host-agnostic by design; only the file a host reads differs.
    """
    mcp_dir = output_dir / "mcp"
    mcp_dir.mkdir(parents=True, exist_ok=True)

    definition = {
        "command": python_executable,
        "args": ["-m", "data2agent.cli", "serve", str(output_dir), "--mode", mode],
        "env": {},
    }
    write_json(mcp_dir / "server.json", {"mcpServers": {"data2agent": definition}})
    (mcp_dir / "USAGE.md").write_text(
        _render_usage(output_dir, source_dir, mode, definition), encoding="utf-8"
    )
    return mcp_dir


def _render(manifest: dict[str, Any], ledger: EvidenceLedger) -> str:
    lines: list[str] = [
        "# Dataset report",
        "",
        "Generated by Data2Agent. Every statement below is backed by a claim in",
        "`evidence.json`; the claim id in brackets is the lookup key for",
        "`get_evidence(claim_id=...)`. Fields that were not determined are named as",
        "such and are never filled in by inference.",
        "",
        "## Identity",
        "",
        f"- Dataset id: `{manifest.get('dataset_id', '')}`",
        f"- Files: {manifest.get('file_count', 0)}",
        f"- Total bytes: {manifest.get('total_bytes', 0)}",
        f"- Manifest version: {manifest.get('manifest_version', '')}",
        "",
    ]

    formats = manifest.get("formats", {})
    if formats:
        lines += ["## Formats", ""]
        lines += [f"- `{name}`: {count} file(s)" for name, count in formats.items()]
        lines.append("")

    metadata_files = manifest.get("metadata_files", [])
    lines += ["## Metadata files", ""]
    if metadata_files:
        for item in metadata_files:
            lines.append(f"- `{item['path']}` — {item['convention']} ({item['note']})")
    else:
        lines.append("- None recognised by filename convention.")
    lines.append("")

    tables = manifest.get("tables", {})
    if tables:
        lines += ["## Tables", ""]
        for path, profile in tables.items():
            lines += [
                f"### `{path}`",
                "",
                f"- Rows: {profile.get('rows', 0)}",
                f"- Columns: {profile.get('column_count', 0)}",
                "",
                "| column | observed shape | missing | null-like tokens | claim |",
                "| --- | --- | --- | --- | --- |",
            ]
            for column in profile.get("columns", []):
                claim = _find_claim(ledger, path, "table.column-dtype", column["name"])
                lines.append(
                    f"| `{column['name']}` | {column['dtype']} | {column['missing']} | "
                    f"{column.get('null_like_tokens', 0)} | `{claim}` |"
                )
            lines.append("")

    identifiers = manifest.get("identifiers", [])
    lines += ["## Identifiers detected", ""]
    if identifiers:
        lines.append(
            "Detected by pattern match only. No identifier was resolved; resolution is "
            "a FAIR check and is not implemented in this version."
        )
        lines.append("")
        for hit in identifiers:
            lines.append(f"- `{hit['scheme']}` `{hit['value']}` — {hit['source']}:{hit['line']}")
    else:
        lines.append("- None detected.")
    lines.append("")

    lines += [
        "## Not determined",
        "",
        "The following were **not** assessed and must not be inferred from this report:",
        "",
        "- Cross-file relationships between tables and metadata records.",
        "- The scientific meaning of any column, including units and controlled terms.",
        "- Whether null-like tokens (`NA`, `unknown`, ...) denote missing values.",
        "- Whether any detected identifier resolves, or is correct.",
        "- Any FAIR indicator. FAIR assessment is a separate profile, planned for v0.2.",
        "",
    ]

    warnings = manifest.get("warnings", [])
    lines += ["## Warnings", ""]
    lines += [f"- {warning}" for warning in warnings] if warnings else ["- None."]
    lines.append("")
    lines += [f"Claims recorded: {len(ledger)}.", ""]
    return "\n".join(lines)


def _find_claim(ledger: EvidenceLedger, subject: str, check: str, field: str) -> str:
    for record in ledger.query(subject=subject, check=check):
        if any(item.field == field for item in record.evidence):
            return record.claim_id
    return "—"


def _render_usage(output_dir: Path, source_dir: Path, mode: str, definition: dict[str, Any]) -> str:
    block = json.dumps({"mcpServers": {"data2agent": definition}}, indent=2)
    command = " ".join([definition["command"], *definition["args"]])
    return f"""# Connecting this dataset's MCP server

This server exposes the dataset ingested from `{source_dir}` in mode `{mode}`.
It is read-only: it never writes to the dataset, and it withholds content from any
file whose checksum no longer matches `manifest.json`.

## Requirements

```bash
pip install 'data2agent[mcp]'
```

## Claude Code

```bash
claude mcp add data2agent -- {command}
```

## Codex and other hosts reading an MCP JSON config

```json
{block}
```

## Any host

The server speaks MCP over stdio and knows nothing about which host started it.
Run it directly with:

```bash
{command}
```

## Available tools in mode `{mode}`

Call `dataset_inventory` first, then `inspect_table` / `get_metadata` for
specifics, and `get_evidence` before asserting anything. A statement with no
supporting claim is unsupported -- report it as unknown.

## Output directory

```
{output_dir}
├── manifest.json     what the dataset is (deterministic; no timestamps)
├── provenance.json   what this ingest run was
├── evidence.json     claim -> evidence -> file -> checksum
├── mcp/              this directory
└── report/           evidence-backed Markdown report
```
"""
